name: Docker Image CI


on:
  # Trigger the action manually from the UI
  workflow_dispatch:
  # Trigger the action when pushing to certain 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./caddy --file Dockerfile --tag my-image-name:$(date +%s)
